#!/usr/bin/env python3
"""
Development helper: writes a tiny, valid WAV file with real RIFF INFO tags so the
upload pipeline (metadata extraction + cover art) can be exercised without
shipping audio fixtures in the repository.

Usage: python3 scripts/make-test-audio.py [output.wav]
"""
import math
import struct
import sys
import wave


def chunk(tag: bytes, payload: bytes) -> bytes:
    pad = b"\x00" if len(payload) % 2 else b""
    return tag + struct.pack("<I", len(payload)) + payload + pad


def info_chunk(fields: dict[str, str]) -> bytes:
    payload = b"INFO"
    for tag, value in fields.items():
        encoded = value.encode("utf-8") + b"\x00"
        payload += chunk(tag.encode("ascii"), encoded)
    return chunk(b"LIST", payload)


def main() -> None:
    out = sys.argv[1] if len(sys.argv) > 1 else "/tmp/tuneroom-sample.wav"
    sample_rate = 44100
    seconds = 6
    frames = bytearray()

    # A short I-vi-IV-V arpeggio so the file actually sounds like something.
    chord_root = [261.63, 220.0, 174.61, 196.0]
    for index in range(sample_rate * seconds):
        t = index / sample_rate
        root = chord_root[int(t // 1.5) % len(chord_root)]
        envelope = 0.5 + 0.5 * math.sin(2 * math.pi * (t % 1.5) / 1.5)
        sample = (
            0.42 * math.sin(2 * math.pi * root * t)
            + 0.22 * math.sin(2 * math.pi * root * 2 * t)
            + 0.10 * math.sin(2 * math.pi * root * 3 * t)
        ) * envelope
        value = int(max(-1.0, min(1.0, sample)) * 32000)
        # Stereo frame: the right channel is delayed slightly for a little width.
        frames += struct.pack("<hh", value, int(value * 0.86))

    pcm = bytes(frames)
    fmt = struct.pack("<HHIIHH", 1, 2, sample_rate, sample_rate * 4, 4, 16)
    info = info_chunk(
        {
            "INAM": "Quiet Hours",
            "IART": "TuneRoom Test Artist",
            "IPRD": "Development Samples",
            "ICMT": "Generated by scripts/make-test-audio.py",
        }
    )

    body = chunk(b"fmt ", fmt) + info + chunk(b"data", pcm)
    with open(out, "wb") as handle:
        handle.write(b"RIFF" + struct.pack("<I", 4 + len(body)) + b"WAVE" + body)

    # Sanity check through the stdlib reader.
    with wave.open(out, "rb") as handle:
        print(
            f"{out}: {handle.getnframes() / handle.getframerate():.1f}s "
            f"{handle.getframerate()}Hz {handle.getnchannels()}ch "
            f"{handle.getsampwidth() * 8}bit"
        )


if __name__ == "__main__":
    main()
